sonar.projectKey=bhoomikamallireddy_Automated_DataAnalysis
sonar.organization=bhoomikamallireddy
sonar.host.url=https://sonarcloud.io

# Scan everything in the root
sonar.sources=.

# Exclusions: This is CRITICAL for your project
# We must exclude the zip files and environment files to prevent errors
sonar.exclusions=**/*.zip, **/node_modules/**, **/venv/**, **/.env, **/migrations/**, **/dist/**

# Tell SonarCloud where the main languages are
sonar.python.version=3.11
sonar.javascript.environments=browser,node
